// <auto-generated />
namespace FlashcardAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NavigationPropertyCardset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NavigationPropertyCardset));
        
        string IMigrationMetadata.Id
        {
            get { return "201907310801483_NavigationPropertyCardset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
